### ISSUE TITLE
Tables in Demos do not contain a border

### ISSUE THREAD

**Issue by tim-thatcher** [tinymce/tinymce-docs#213]
@kilianc The CSS used for the TinyMCE demos don't include a visible border for tables.  One of the new features of 4.3 is to be able to resize table cols/rows by using a drag handle on the border.  Not having a visible border makes this harder.  Please change the CSS so that the tables borders are visible.  Thanks.

**Comment by kilianc** [comment]
@tim-thatcher @r12s is this still valid?

![](https://www.dropbox.com/s/ghjtpl2k0yhjpqf/Screenshot%202016-03-05%2012.15.37.png?dl=1)

Before moving forward I wanted to double check if this is yet not acceptable, looks pretty straight forward to me, I think the tables style got fixed in Jan.

Please advice if I should restore default table aspect which is:

![](https://www.dropbox.com/s/8xikyr2pn0qi175/Screenshot%202016-03-05%2012.17.21.png?dl=1)

**Comment by tim-thatcher** [comment]
@kilianc I still have the same comment.  The example doesn't include cell borders.  It's a lot more obvious for people to be able to see where to grab in order to resize the table columns, which was a new feature of the latest release.  I would like to see cell borders in the example table.

**Comment by r12s** [comment]
This now looks resolved. Confirming @tim-thatcher?

**Comment by tim-thatcher** [comment]
Yep...had to flush the cache to see it.  Thanks.  will close.
